---
##########################################################################################################
#       _____ __ __  ____  __ __  ____  __ __   ____  _           ____   ____  ___ ___    ___  ____      #
#      / ___/|  |  ||    \|  |  ||    ||  |  | /    || |         /    | /    ||   |   |  /  _]/ ___/     #
#     (   \_ |  |  ||  D  )  |  | |  | |  |  ||  o  || |        |   __||  o  || _   _ | /  [_(   \_      #
#      \__  ||  |  ||    /|  |  | |  | |  |  ||     || |___     |  |  ||     ||  \_/  ||    _]\__  |     #
#      /  \ ||  :  ||    \|  :  | |  | |  :  ||  _  ||     |    |  |_ ||  _  ||   |   ||   [_ /  \ |     #
#      \    ||     ||  .  \\   /  |  |  \   / |  |  ||     |    |     ||  |  ||   |   ||     |\    |     #
#       \___| \__,_||__|\_| \_/  |____|  \_/  |__|__||_____|    |___,_||__|__||___|___||_____| \___|     #
#                                                                                                        #
#                Hi, thanks for downloading "SurvivalGame" plugin for pocketmine,                        #
#                                                                                                        #
#          This plugin is being made, So therefore new bugs /features are being added                    #
#                   Below are some configuration file for this plugin                                    #
##########################################################################################################




########################
# Message 
########################
Player_Join_Server: Welcome To My Server 
ArenaJoin: Joinning SG Match.........
Arenajoined: You have join SG-1
ArenaFullMessage: Tournament Is Full, Join Later


########################################################
# Arena's #
########################################################
Lobby: Lobby    // This will be where player's get teleported after they die / win match.
Arena: SG   // The world the plugin will use to teleport the player to the arena.

Min-Player: 2 // Cannot be changed! 'YET"
Max-Player: 24 // Cannot be changed! 'YET"


# Stand Where you wan't to set spawn and do /xyz and add the number's in config
# Add The same line for more player's
Pos_Spawn:
- - 1      // X
  - 2     //  Y   Add The 3 Line, For each player spawn.
  - 3     //  Z
---
