---
#####
# Surviva Game Plugin
# Made By: Andre_The_Gamer
#####


##
# Arena's #
##
arena1
  Lobby-World: Lobby    // This will be where player's get teleported after they die / win match
     Match-World: SG   // The world the plugin will use to teleport the player to the arena



---
